[project]
name = "aqumenlib"
description = "AQUMEN SDK"
readme = "README.md"
authors = [
    { name = "Aqumen Technology Solutions Ltd", email = "denys@aqumen.io" }
]
license = { file = "LICENCE" }
dependencies = [
  "QuantLib",
  "pandas",
  "toml",
  "pydantic",
  "peewee",
  "pytest",
]
version = "0.1.0"
requires-python = ">= 3.11"

[project.urls]
Homepage = "https://aqumen.io"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120
# Maximum number of lines in a module.
max-module-lines = 1000

[tool.pylint.classes]
# List of method names used to declare (i.e. assign) instance attributes.
defining-attr-methods = ["__init__", "__new__", "setUp", "asyncSetUp", "__post_init__", "model_post_init"]

[tool.black]
line-length = 120
target-versions = ["py37", "py38", "py39", "py310", "py311"]
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
